Move CAPA userconfig values to global chart values
giantswarm/capi-migration-cli pull request #4
Opened 2023-11-30 12:33 UTC by njuettner

2023-11-30 12:33 UTC, njuettner commented on pkg/migrator/capi_app.go
> +	ClusterAppVersion  = "0.50.0"
Placeholder

2023-11-30 13:44 UTC, calvix commented
Once the new release is ready I would like to test this work before merging, as many values could changed in the cluster-aws so I want to be sure it still works.

2023-12-05 10:41 UTC, njuettner commented
@calvix there's a release of the global changes in cluster-aws `v0.50.0`, I think you should be able now to test it.

2023-12-05 12:27 UTC, bdehri commented
@njuettner do we need to update `kubectl gs` as well?

2023-12-05 12:33 UTC, njuettner commented
@bdehri that was already done using the latest kubectl-gs should work 🙂

2023-12-05 12:52 UTC, njuettner commented on go.mod
> +	k8s.io/api v0.28.4
I cannot update to v0.27.x because it's broken due to dependencies, more details here https://github.com/kubernetes/client-go/issues/1269

2023-12-11 13:27 UTC, calvix commented
I will try this now

2023-12-11 15:36 UTC, calvix requested changes
It looks like the migration process is now broken, I do not know if the values change is the cause or something else. I will need to investigate further with debug mode on cluster-aws, but for now let's block the PR

2023-12-12 11:01 UTC, calvix approved these changes
Not sure what was wrong but next 3 runs finished without issue so probably nothing tied to this change

2023-12-12 11:02 UTC, calvix commented
I did a small change to avoid having a error message from controller runtime about not using log

2023-12-12 11:22 UTC, merged